apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels:
    app: "my-nginx"
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: "my-nginx"
    spec:
      containers:
      - name: my-pod
        image: nginx:1.17.9-alpine
  replicas: 2
  selector:
    matchLabels:
       app: "my-nginx"
